<a href="https://colab.research.google.com/github/tor504/python/blob/main/practice_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# (실습) 넘파이 어레이

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

## numpy 모듈

**문제 1**

아래 코드를 설명하라.

In [ ]:
import numpy as np

`코드설명`: 이 코드는 파이썬에서 NumPy 라이브러리를 임포트(import)하는 코드

아래 코드는 수정하지 마세요!!!

In [ ]:
import numpy as np

np.__version__

'1.25.2'

**문제 2**

아래 코드의 기능을 설명하라

In [ ]:
np.random.seed(42)

`코드설명`: NumPy의 난수 생성기에 시드(seed) 값을 설정하는 역할

**문제 3**

부동소수점으로 구성된 어레이의 항목은 기본적으로 소수점 이하 8자리까지 출력한다.

In [ ]:
Z = np.random.random((40,40))
Z

array([[0.12384603, 0.07053564, 0.9094295 , ..., 0.41351653, 0.03981144,
        0.2739881 ],
       [0.95564947, 0.95363261, 0.35232705, ..., 0.69607986, 0.36250198,
        0.82399765],
       [0.20408766, 0.46904075, 0.80093872, ..., 0.37208225, 0.75982366,
        0.33882348],
       ...,
       [0.82686785, 0.56265542, 0.76218751, ..., 0.57718668, 0.64772005,
        0.02929944],
       [0.61810297, 0.50950887, 0.54574968, ..., 0.45820481, 0.94501709,
        0.67360983],
       [0.06489928, 0.46572558, 0.24024502, ..., 0.32953041, 0.44060311,
        0.85695013]])

`np.set_printoptions()` 의 기능을 다음 두 개의 예를 이용하여 설명하라.

In [ ]:
np.set_printoptions(precision=4)

In [ ]:
Z

array([[0.12384603, 0.07053564, 0.9094295 , ..., 0.41351653, 0.03981144,
        0.2739881 ],
       [0.95564947, 0.95363261, 0.35232705, ..., 0.69607986, 0.36250198,
        0.82399765],
       [0.20408766, 0.46904075, 0.80093872, ..., 0.37208225, 0.75982366,
        0.33882348],
       ...,
       [0.82686785, 0.56265542, 0.76218751, ..., 0.57718668, 0.64772005,
        0.02929944],
       [0.61810297, 0.50950887, 0.54574968, ..., 0.45820481, 0.94501709,
        0.67360983],
       [0.06489928, 0.46572558, 0.24024502, ..., 0.32953041, 0.44060311,
        0.85695013]])

In [ ]:
np.set_printoptions(precision=6)

In [ ]:
Z

array([[0.123846, 0.070536, 0.90943 , ..., 0.413517, 0.039811, 0.273988],
       [0.955649, 0.953633, 0.352327, ..., 0.69608 , 0.362502, 0.823998],
       [0.204088, 0.469041, 0.800939, ..., 0.372082, 0.759824, 0.338823],
       ...,
       [0.826868, 0.562655, 0.762188, ..., 0.577187, 0.64772 , 0.029299],
       [0.618103, 0.509509, 0.54575 , ..., 0.458205, 0.945017, 0.67361 ],
       [0.064899, 0.465726, 0.240245, ..., 0.32953 , 0.440603, 0.85695 ]])

`코드설명`: NumPy가 배열을 출력할 때 소수점 이하의 자릿수를 설정하는 함수입니다. 여기서는 소수점 이하 4자리,6자리까지 표시하도록 설정

아래 코드는 기본 옵션값으로 되돌린다. 수정하지 마세요.

In [ ]:
np.set_printoptions(precision=8)

## 1차원 어레이

**문제 1**

크기가 10이고 모든 항목이 0인 1차원 어레이를
변수 `Z`가 가리키도록 하라.
단, `np.zeros()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 10에서 49까지의 정수 중에서 짝수로만 구성된 1차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(10,49,2)
Z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
                        44, 46, 48])).all()

**문제 3**

변수 `Z`가 아래와 같이 선언되었다.

In [ ]:
Z = np.array([2, 3, 1, 0, 4])
Z

array([2, 3, 1, 0, 4])

변수 `Z`의 항목을 정렬하라.
단, sort() 메서드를 활용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
np.sort(Z)
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.arange(5)).all()

**문제 4**

변수 `Z`가 크기 30이며 무작위로 생성된 1차원 어레이를 가리키도록 하라.
또한 포함된 항목들의 평균값을 계산하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
`np.random.random()` 함수, `mean()` 어레이 메서드를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random(30)
print(Z)
Z_mean = np.mean(Z)
print(Z_mean)

[0.57248914 0.41485672 0.74129125 0.90040758 0.1612752  0.82684588
 0.3267662  0.47469194 0.80588234 0.66975126 0.86642459 0.81158427
 0.26378598 0.088789   0.19607346 0.25673032 0.90566125 0.12478297
 0.28125105 0.78485013 0.51375522 0.57334447 0.84273156 0.80207794
 0.70413584 0.47107738 0.96484966 0.08190529 0.35251244 0.4465952 ]
0.5409058510086472


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (30,))
print(f"1차원 어레이 평균값: {Z_mean}")

1차원 어레이 평균값: 0.5409058510086472


**문제 5**

1차원 어레이가 다음과 같이 주어졌다.

In [ ]:
Z = np.arange(1, 4)
Z

array([1, 2, 3])

(1) 아래 표현식의 계산 결과를 설명하라.

In [ ]:
Z*Z

array([1, 4, 9])

`코드설명`:

(2) 아래 표현식의 계산 결과를 설명하라.

In [ ]:
Z**Z

array([ 1,  4, 27])

`코드설명`: 이는 각 요소를 제곱한 값들이 포함된 배열

(3) 아래 표현식의 계산 결과를 설명하라.

In [ ]:
Z < -Z

array([False, False, False])

`코드설명`: Z가 [1, 2, 3]일 때, -Z는 [-1, -2, -3]이 됩니다. 따라서 요소별로 비교하면 [1 < -1, 2 < -2, 3 < -3]이 됩니다. 이는 다음과 같이 계산됩니다:각 요소가 자신의 음수보다 작은지 여부를 나타내는 부울 배열

(4) 아래 표현식의 계산 결과를 설명하라.

In [ ]:
Z/1/1

array([1., 2., 3.])

`코드설명`: Z가 1부터 3까지의 값을 가지는 NumPy 배열일 때, Z/1/1은 각 요소를 1로 나눈 후 다시 1로 나눈 값을 반환 각 요소를 1로 나눈 후 다시 1로 나눈 값들을 나타냅니다.

**문제 6**

변수 `Z`가 아래 모양의 어레이를 가리키도록 하라.
단, `np.linspace()` 함수와 `endpoint` 키워드 인자를 이용한다.

```
[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.linspace(0,0.9,num = 10,endpoint=True)
Z

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert np.isclose(Z, np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])).all()

**문제 7**

아래 코드의 실행결과를 설명하라.

In [ ]:
Z = np.zeros((10,10)) #이 코드는 10x10 크기의 모든 요소가 0으로 채워진 2차원 NumPy 배열을 생성하고, 이 배열이 차지하는 메모리 크기를 계산하여 바이트 단위로 출력하는 것입니다.
print("%d bytes" % (Z.size * Z.itemsize)) # 배열이 차지하는 메모리 크기 출력

800 bytes


`코드설명`: 10x10 크기의 모든 요소가 0으로 채워진 2차원 NumPy 배열을 생성하고, 이 배열이 차지하는 메모리 크기를 계산하여 바이트 단위로 출력하는 것입니다.

**문제 8**

다음 리스트에서 0이 아닌 항목들의 인덱스로 구성된 어레이를 한줄 코드로 생성하라.
단. `np.nonzero()` 함수를 활용한다.

In [ ]:
Z = [1, 2, 0, 0, 4, 0]

In [ ]:
# None을 적절한 표현식으로 대체하라.
non_zeros = np.nonzero(Z)
print(non_zeros)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4]))


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (non_zeros == np.array([0, 1, 4])).all()

**문제 9**

두 개의 1차원 어레이가 다음과 같이 주어졌다.

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2

아래 코드의 실행 결과를 설명하라.

In [ ]:
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

`코드설명`: A와 B를 각각 생성합니다.

A는 1로 이루어진 크기가 3인 1차원 배열이 되며, [1. 1. 1.]입니다.
B는 2로 이루어진 크기가 3인 1차원 배열이 되며, [2. 2. 2.]입니다.
A와 B를 더한 후, -A/2를 곱합니다.

A+B는 [3. 3. 3.]이 됩니다.
-A/2는 [[-0.5 -0.5 -0.5], [-0.5 -0.5 -0.5], [-0.5 -0.5 -0.5]]가 됩니다. (브로드캐스팅 연산에 의해 각 요소가 -0.5로 계산됩니다.)
위의 두 배열을 곱합니다.

(A+B)*(-A/2)는 [[ -1.5 -1.5 -1.5], [ -1.5 -1.5 -1.5], [ -1.5 -1.5 -1.5]]가 됩니다.
따라서 결과로는 -1.5로 이루어진 2차원 배열이 반환

In [ ]:
np.add(A,B,out=B)

array([3., 3., 3.])

`코드설명`:
np.add(A, B, out=B)는 두 개의 배열 A와 B를 더한 후 결과를 B에 저장하는 연산입니다.

여기서 A와 B는 이미 생성된 배열이고, out 매개변수를 사용하여 연산 결과를 B에 저장하도록 지시하고 있습니다.

따라서 A와 B를 더한 결과는 B에 저장되어 B의 내용이 변경됩니다. 즉, B의 값은 [1. 1. 1.]에서 [3. 3. 3.]으로 바뀌게 됩니다.

In [ ]:
np.divide(A,2,out=A)

array([-0.09375, -0.09375, -0.09375])

`코드설명`: np.divide(A, 2, out=A)는 배열 A의 모든 요소를 2로 나눈 후 그 결과를 다시 배열 A에 저장하는 연산입니다.

여기서 A는 이미 생성된 배열이고, out 매개변수를 사용하여 연산 결과를 A에 저장하도록 지시하고 있습니다.

따라서 A의 모든 요소가 2로 나눠진 후 그 결과가 다시 A에 저장됩니다. 따라서 A의 값은 [1. 1. 1.]에서 [0.5 0.5 0.5]로 변경됩니다.

In [ ]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

`코드설명`: np.negative(A, out=A)는 배열 A의 모든 요소를 부정(negative)한 후 그 결과를 다시 배열 A에 저장하는 연산입니다.

여기서 A는 이미 생성된 배열이고, out 매개변수를 사용하여 연산 결과를 A에 저장하도록 지시하고 있습니다.

따라서 A의 모든 요소에 대해 부정 연산이 수행되고, 그 결과가 다시 A에 저장됩니다. 예를 들어, [0.5, 0.5, 0.5]의 경우 -0.5, -0.5, -0.5가 되어 배열 A에 저장

In [ ]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

`코드설명`: np.multiply(A, B, out=A)는 두 개의 배열 A와 B의 요소별 곱셈을 수행한 후 결과를 다시 배열 A에 저장하는 연산입니다.

여기서 A와 B는 이미 생성된 배열이고, out 매개변수를 사용하여 연산 결과를 A에 저장하도록 지시하고 있습니다.

따라서 A와 B의 요소별 곱셈이 수행되고, 그 결과가 다시 A에 저장됩니다. 이는 각각의 요소별로 곱셈이 이루어지므로 결과는 [1 * 3, 1 * 3, 1 * 3] 즉 [3, 3, 3]이 되어 배열 A에 저장됩니다.

## 2차원 어레이

**문제 1**

변수 `Z`가 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random((5,5))
Z

array([[0.32200271, 0.70844457, 0.68983597, 0.77519908, 0.97203772],
       [0.04111446, 0.8921423 , 0.93311795, 0.94764889, 0.92358193],
       [0.31209555, 0.47184125, 0.07952485, 0.39885599, 0.32194123],
       [0.63714165, 0.49073778, 0.82794053, 0.68877797, 0.61837552],
       [0.2808026 , 0.9579426 , 0.95068891, 0.29964537, 0.73162882]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (5, 5))
assert (Z.dtype == np.float64)

**문제 2**

변수 `Z`가 0에서 8까지의 정수로 이루어진 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# np.arange() 함수를 사용하여 0에서 8까지의 정수를 생성하고 reshape() 메서드를 사용하여 (3, 3) 모양의 2차원 어레이로 변환합니다.
Z = np.arange(9).reshape(3, 3)

print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])).all()

**문제 3**

변수 `Z`가 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, 2차원 어레이의 대각선 상은 1이고 나머지는 0이어야 한다.
또한 `np.eye()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

Z = np.eye(3)

print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all

**문제 4**

변수 `Z`가 아래와 같은 (5,5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `np.diag()` 함수의 `k` 키워드 인자를 반드시 활용한다.

```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = np.diag(np.arange(1,5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0],
                        [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0],
                        [0, 0, 0, 4, 0]])).all()

**문제 5**

변수 `Z`가 아래와 같은 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수, `np.arange()` 함수, 2차원 어레이 덧셈을 이용한다.

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# np.arange() 함수를 사용하여 0에서 4까지의 정수를 생성하고 reshape() 메서드를 사용하여 (1, 5) 모양의 2차원 어레이로 변환합니다.
arr = np.arange(5).reshape(1, 5)

# np.zeros() 함수를 사용하여 모든 요소가 0인 (5, 5) 모양의 2차원 어레이를 생성합니다.
zeros_arr = np.zeros((5, 5))

# 두 어레이를 더하여 변수 Z에 할당합니다.
Z = arr + zeros_arr

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.]])).all()

**문제 6**

아래 3x3 단위 행렬에 해당하는 2차원 어레이를 한줄 코드로 생성하라.
단, `np.eye()` 함수를 이용한다.

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all()

**문제 7**

무작위 수로 구성된 (5, 5) 모양의 2차원 어레이가 다음과 같다.

In [ ]:
Z = np.random.random((5, 5))

변수 `Z`가 가리키는 2차원 어레이에 대해 min-max 크기조정(정규화)을 적용하라.

min-max 크기조정(정규화)은 항목의 모든 값을 아래 식을 통해 0과 1 사이의 부동소수점으로 변환한다. $max$와 $min$은 각각 최대 항목과 최소 항목을 가리킨다.

$$
\frac{x-min}{max - min}
$$

In [ ]:
Z = (Z - Z.min()) / (Z.max() - Z.min())
Z

array([[0.40095628, 0.85383929, 0.5587484 , 0.7786887 , 0.82577256],
       [0.63164195, 0.33157493, 0.50566974, 0.44804048, 0.75549688],
       [0.66003013, 0.74363987, 1.        , 0.38228511, 0.90502926],
       [0.        , 0.65713614, 0.22872178, 0.07212383, 0.66739822],
       [0.41161464, 0.73327303, 0.44046399, 0.17586503, 0.80706354]])

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.max() == 1 and Z.min() == 0)

## 3차원 어레이

**문제 1**

(1) 변수 `Z`가 (3, 3, 3) 모양의 3차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np
Z = np.random.random((3,3,3))
print(Z)
print(Z.shape)
print(Z.dtype)

[[[0.05101668 0.7596113  0.2918252 ]
  [0.66464112 0.72461102 0.26898231]
  [0.273065   0.65565915 0.23529709]]

 [[0.64130772 0.84104328 0.96658622]
  [0.6985222  0.13951389 0.40240153]
  [0.53538265 0.91903121 0.22478481]]

 [[0.47412903 0.99692049 0.622288  ]
  [0.90486647 0.22752884 0.98652392]
  [0.32540699 0.1828396  0.56304899]]]
(3, 3, 3)
float64


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (3, 3, 3))
assert (Z.dtype == 'f8')

(2) `Z`에 포함된 항목들 중에서 최댓값과 최솟값의 차이를 구하라.
단, `maximum`, `mininum` 두 변수가 각각 최댓값과 최솟값을 가리키도록 하며,
`max()`와 `min()` 어레이 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# (5, 5) 모양의 무작위 값으로 채워진 배열 생성
Z = np.random.random((5, 5))

# 배열의 최댓값과 최솟값 계산
maximum = Z.max()
minimum = Z.min()

# 최댓값과 최솟값의 차이 계산
difference = maximum - minimum

print("최댓값:", maximum)
print("최솟값:", minimum)
print("최댓값과 최솟값의 차이:", difference)

최댓값: 0.9947577318254426
최솟값: 0.03119053404352623
최댓값과 최솟값의 차이: 0.9635671977819164


아래 코드는 수정하지 마세요!!!

In [ ]:
print(f"최댓값과 최솟값의 차이: {maximum - minimum}")

최댓값과 최솟값의 차이: 0.9635671977819164


## `dtype` 종류

**문제 1**

아래 두 코드의 실행결과를 설명하라.

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


`코드설명`:각 데이터 타입에 대한 최솟값과 최댓값이 출력됩니다. 이 정보를 사용하여 해당 데이터 타입으로 저장할 수 있는 값의 범위를 확인

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


`코드설명`:각 부동소수점 데이터 타입에 대한 최솟값, 최댓값, 그리고 최소 유효 비트(가장 작은 수와 그 수의 다음 표현 가능한 수 사이의 차이)가 출력

**문제 2**

부동소수점으로 구성된 1차원 어레이가 아래와 같이 주어졌다.

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)

변수 `Y`가 변수 `Z`가 가리키는 1차원 어레이의 dtype이 `int32`로 형변환된 1차원 어레이를 가리키도록 하라.
단, `astype()` 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# 변수 Z가 가리키는 1차원 어레이 생성
Z = (np.random.rand(10)*100).astype(np.float32)

# int32로 형변환된 1차원 어레이 생성
Y = Z.astype(np.int32)

print(Y)

[12 19 64 76 29 77 14 47 44 57]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y.shape == (10,))
assert (Y.dtype == np.int32)

**문제 3**

변수 `Z`가 아래와 같이 무작위로 생성된 길이가 10인 1차원 어레이를 가리킨다.

In [ ]:
Z = np.random.uniform(0,10,10)
Z

array([5.26244603, 8.20008368, 3.64221848, 4.39835732, 3.17239933,
       9.22728533, 1.98584495, 6.36437528, 0.79585042, 2.99868701])

(1) 나머지 연산자(`%`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# (0, 10) 범위에서 균일한 분포를 가진 10개의 무작위 실수 생성
Z = np.random.uniform(0, 10, 10)

# 정수로만 구성된 어레이 Y 생성
Y = Z.astype(int) % 10

print(Y)

[9 5 4 9 1 4 4 2 8 6]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(2) 몫 연산자(`//`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# (0, 10) 범위에서 균일한 분포를 가진 10개의 무작위 실수 생성
Z = np.random.uniform(0, 10, 10)

# 정수로만 구성된 어레이 Y 생성
Y = Z.astype(int) // 1

print(Y)

[2 3 8 9 7 9 2 4 8 2]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(3) 내림 함수 `np.floor()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# (0, 10) 범위에서 균일한 분포를 가진 10개의 무작위 실수 생성
Z = np.random.uniform(0, 10, 10)

# 정수로만 구성된 어레이 Y 생성
Y = np.floor(Z).astype(int)

print(Y)

[7 6 2 2 8 2 6 9 9 2]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(4) `np.trunc()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
import numpy as np

# (0, 10) 범위에서 균일한 분포를 가진 10개의 무작위 실수 생성
Z = np.random.uniform(0, 10, 10)

# 정수로만 구성된 어레이
Y = np.trunc(Z).astype(int)

print(Y)

[7 3 0 2 1 7 8 0 7 5]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()